name: Build VFX v1.5

on:
  push:
    branches:
      - audio-wave-vfx-v1
    paths:
      - src/audio-shader-source.cpp
      - src/includes/audio-shader-source.hpp
      - .github/workflows/build-vfx-v1-5.yaml

jobs:
  build:
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
