name: Build Internal Render Scale v1

on:
  push:
    branches:
      - audio-wave-vfx-v1
    paths:
      - .github/workflows/build-render-scale-v1.yaml

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build-project.yaml
    secrets: inherit
